services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=hopital
      - MYSQL_ROOT_PASSWORD=MySQL08022000
    networks:
      - hopital_api
    ports:
      - 3307:3306
    volumes:
          - ./:/docker-entrypoint-initdb.d
          - db:/var/lib/mysql
    healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
            timeout: 20s
            retries: 10

  api:
    image: thomas6a/hopitalapi:latest
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/hopital
      - server.port=8080
    networks:
      - hopital_api
    depends_on:
      db:
          condition: service_healthy

networks:
  hopital_api:
    driver: bridge
          
volumes:
    db:
      driver: local
        
    
